### ISSUE TITLE
how did you host the API

### ISSUE THREAD

**Issue by nabilnabawi1234** [GustavoBarros11/rossmann_sales_forecast#1]
Can you provide me with a way to host the API?
I hosted the API in render, and it was working, but there were some errors. Can you provide me files you have hosted in Render? I would appreciate it. thanks

**Comment by GustavoBarros11** [comment]
Hello, thanks for your interest in my project! I hosted it on Render too, the files in Render for the API are the ones inside the  rossmann-api folder in this repository. I have also just fixed a small bug on the rossmann-api/handler.py file that prevented the api from working properly, after that i tested locally and it was all working just fine.
